### ISSUE TITLE
How to show the user the situations that the service is relvant to?

### ISSUE THREAD

**Issue by akariv** [whiletrue-industries/srm-frontend#7]
Right now we're just showing the responses - but not the situations. 
How should we do that (design wise)?

This is also useful from an SEO standpoint.

**Comment by mushon** [comment]
Is that a phase 2 consideration?

**Comment by akariv** [comment]
At the moment there's no visible indication as to which target audiences a
service is intended for.
For example, if I filter for lgbtq + haredi hostels, I will get first those
that match both criteria and later hostels that match one of them.
There's no way for the user to know which target audiences the service has
that match those being filtered (or generally).

**Comment by mushon** [comment]
I’m not arguing against it’s necessity. I completely agree this is an oversight. Let’s prioritize this for early in phase 2 then.

**Comment by akariv** [comment]
Yes, this has not come up as a feedback from anyone.

**Comment by amitaykorn** [comment]
תחשבו שברוב המקרים שירות מייצג כמה אוכלוסיות who. ע"ע הוסטל למתמודדי נפש וחרדים. יש היגיון להציג אותן. ברור שצריך לחשוב על עיצוב (האם להפריד ויזואלית בין מי למה? האם זה מעניין את המשתמשים?). בנוסף אשמח אם הממשק יאפשר לי ללחוץ על תגית "חרדים" ואז לראות את כלל השירותים לחרדים בפוקקוס של המפה.

**Comment by akariv** [comment]
Closing in favor of https://github.com/kolzchut/srm/issues/107
